FROM golang:1.21 AS builder
WORKDIR /src

ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd

RUN go build -o /emitter ./cmd/emitter

FROM gcr.io/distroless/base-debian12
COPY --from=builder /emitter /emitter
ENTRYPOINT ["/emitter"]
